name: "Continuous Integration"

on: [ push, pull_request ]

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          tools: composer:v2

      - name: Install dependencies with composer
        run: composer install -ov

      - name: Run vimeo/psalm
        run: ./vendor/bin/psalm --config=psalm.xml --shepherd

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          tools: composer:v2

      - name: Install dependencies with composer
        run: composer install -ov

      - name: Run phpstan/phpstan
        run: ./vendor/bin/phpstan analyse src --level 7

  phpunit:
    name: PHPUnit

    runs-on: ubuntu-latest

    env:
      PHP_EXTENSIONS: curl, mbstring, dom, intl, json, libxml, xml, xmlwriter, sockets

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: ${{ env.PHP_EXTENSIONS }}
          tools: composer:v2

      - name: Install dependencies
        run: composer update -ov

      - name: Run RabbitMQ
        uses: getong/rabbitmq-action@v1.2
        with:
          rabbitmq version: 3.8.2-management-alpine
          rabbitmq user: guest
          rabbitmq password: guest
          rabbitmq vhost: /

      - name: Set RabbitMQ URL in environment
        run: echo "RIDGE_TEST_DSN=amqp://guest:guest@127.0.0.1:5672//?heartbeat=0" >> $GITHUB_ENV

      - name: Run tests with phpunit
        continue-on-error: true
        run: php ./vendor/bin/phpunit --coverage-clover=coverage.clover && docker logs $(docker ps --format "{{.Names}}")

      - name: Info
        run: |
          docker logs $(docker ps --format "{{.Names}}")

      - name: Upload coverage file
        uses: actions/upload-artifact@v2
        with:
          name: phpunit.coverage
          path: coverage.clover

  upload_coverage:
    name: Upload coverage
    runs-on: ubuntu-latest
    needs: phpunit
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: composer

      - name: Download coverage files
        uses: actions/download-artifact@v2
        with:
          path: reports

      - name: Send code coverage report to Scrutinizer
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover ./reports/phpunit.coverage/coverage.clover